name: AI Improve XLSplitter

on:
  issues:
    types: [labeled, opened, edited]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write
  actions: write
  checks: write
  statuses: write

jobs:
  ai_improve:
    if: |
      (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'ai:improve'))
      || (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/ai-fix'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run AI Improvement
        env:
          LLM_API_URL: ${{ secrets.LLM_API_URL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_MODEL: ${{ secrets.LLM_MODEL }}
        run: python .github/scripts/ai_xlsplitter_improve.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: "AI: Patch generated by Moonshot"
          title: "AI: Improvement from issue trigger"
          body: "This pull request was automatically generated from an issue or comment using the Moonshot LLM."
          branch: ai/fix-${{ github.run_id }}